package org.jcodec.containers.mp4;

import org.jcodec.containers.mp4.boxes.Box;
import org.jcodec.containers.mp4.boxes.ChunkOffsets64Box;
import org.jcodec.containers.mp4.boxes.ChunkOffsetsBox;
import org.jcodec.containers.mp4.boxes.ClearApertureBox;
import org.jcodec.containers.mp4.boxes.ClipRegionBox;
import org.jcodec.containers.mp4.boxes.CompositionOffsetsBox;
import org.jcodec.containers.mp4.boxes.DataInfoBox;
import org.jcodec.containers.mp4.boxes.DataRefBox;
import org.jcodec.containers.mp4.boxes.EditListBox;
import org.jcodec.containers.mp4.boxes.EncodedPixelBox;
import org.jcodec.containers.mp4.boxes.FileTypeBox;
import org.jcodec.containers.mp4.boxes.GenericMediaInfoBox;
import org.jcodec.containers.mp4.boxes.HandlerBox;
import org.jcodec.containers.mp4.boxes.IListBox;
import org.jcodec.containers.mp4.boxes.KeysBox;
import org.jcodec.containers.mp4.boxes.LoadSettingsBox;
import org.jcodec.containers.mp4.boxes.MediaBox;
import org.jcodec.containers.mp4.boxes.MediaHeaderBox;
import org.jcodec.containers.mp4.boxes.MediaInfoBox;
import org.jcodec.containers.mp4.boxes.MetaBox;
import org.jcodec.containers.mp4.boxes.MovieBox;
import org.jcodec.containers.mp4.boxes.MovieExtendsBox;
import org.jcodec.containers.mp4.boxes.MovieExtendsHeaderBox;
import org.jcodec.containers.mp4.boxes.MovieFragmentBox;
import org.jcodec.containers.mp4.boxes.MovieFragmentHeaderBox;
import org.jcodec.containers.mp4.boxes.MovieHeaderBox;
import org.jcodec.containers.mp4.boxes.MsrtBox;
import org.jcodec.containers.mp4.boxes.MtagBox;
import org.jcodec.containers.mp4.boxes.NameBox;
import org.jcodec.containers.mp4.boxes.NodeBox;
import org.jcodec.containers.mp4.boxes.PartialSyncSamplesBox;
import org.jcodec.containers.mp4.boxes.ProductionApertureBox;
import org.jcodec.containers.mp4.boxes.SampleDescriptionBox;
import org.jcodec.containers.mp4.boxes.SampleSizesBox;
import org.jcodec.containers.mp4.boxes.SampleToChunkBox;
import org.jcodec.containers.mp4.boxes.SegmentIndexBox;
import org.jcodec.containers.mp4.boxes.SegmentTypeBox;
import org.jcodec.containers.mp4.boxes.SoundMediaHeaderBox;
import org.jcodec.containers.mp4.boxes.SyncSamplesBox;
import org.jcodec.containers.mp4.boxes.TimeToSampleBox;
import org.jcodec.containers.mp4.boxes.TimecodeMediaInfoBox;
import org.jcodec.containers.mp4.boxes.TrackExtendsBox;
import org.jcodec.containers.mp4.boxes.TrackFragmentBaseMediaDecodeTimeBox;
import org.jcodec.containers.mp4.boxes.TrackFragmentBox;
import org.jcodec.containers.mp4.boxes.TrackFragmentHeaderBox;
import org.jcodec.containers.mp4.boxes.TrackHeaderBox;
import org.jcodec.containers.mp4.boxes.TrakBox;
import org.jcodec.containers.mp4.boxes.TrunBox;
import org.jcodec.containers.mp4.boxes.UdtaBox;
import org.jcodec.containers.mp4.boxes.VideoMediaHeaderBox;

public class DefaultBoxes extends Boxes {
    public DefaultBoxes() {
        ((Boxes) this).mappings.put(MovieExtendsBox.fourcc(), MovieExtendsBox.class);
        ((Boxes) this).mappings.put(MovieExtendsHeaderBox.fourcc(), MovieExtendsHeaderBox.class);
        ((Boxes) this).mappings.put(SegmentIndexBox.fourcc(), SegmentIndexBox.class);
        ((Boxes) this).mappings.put(SegmentTypeBox.fourcc(), SegmentTypeBox.class);
        ((Boxes) this).mappings.put(TrackExtendsBox.fourcc(), TrackExtendsBox.class);
        ((Boxes) this).mappings.put(VideoMediaHeaderBox.fourcc(), VideoMediaHeaderBox.class);
        ((Boxes) this).mappings.put(FileTypeBox.fourcc(), FileTypeBox.class);
        ((Boxes) this).mappings.put(MovieBox.fourcc(), MovieBox.class);
        ((Boxes) this).mappings.put(MovieHeaderBox.fourcc(), MovieHeaderBox.class);
        ((Boxes) this).mappings.put(TrakBox.fourcc(), TrakBox.class);
        ((Boxes) this).mappings.put(TrackHeaderBox.fourcc(), TrackHeaderBox.class);
        ((Boxes) this).mappings.put("edts", NodeBox.class);
        ((Boxes) this).mappings.put(EditListBox.fourcc(), EditListBox.class);
        ((Boxes) this).mappings.put(MediaBox.fourcc(), MediaBox.class);
        ((Boxes) this).mappings.put(MediaHeaderBox.fourcc(), MediaHeaderBox.class);
        ((Boxes) this).mappings.put(MediaInfoBox.fourcc(), MediaInfoBox.class);
        ((Boxes) this).mappings.put(HandlerBox.fourcc(), HandlerBox.class);
        ((Boxes) this).mappings.put(DataInfoBox.fourcc(), DataInfoBox.class);
        ((Boxes) this).mappings.put("stbl", NodeBox.class);
        ((Boxes) this).mappings.put(SampleDescriptionBox.fourcc(), SampleDescriptionBox.class);
        ((Boxes) this).mappings.put(TimeToSampleBox.fourcc(), TimeToSampleBox.class);
        ((Boxes) this).mappings.put(SyncSamplesBox.STSS, SyncSamplesBox.class);
        ((Boxes) this).mappings.put(PartialSyncSamplesBox.STPS, PartialSyncSamplesBox.class);
        ((Boxes) this).mappings.put(SampleToChunkBox.fourcc(), SampleToChunkBox.class);
        ((Boxes) this).mappings.put(SampleSizesBox.fourcc(), SampleSizesBox.class);
        ((Boxes) this).mappings.put(ChunkOffsetsBox.fourcc(), ChunkOffsetsBox.class);
        ((Boxes) this).mappings.put("keys", KeysBox.class);
        ((Boxes) this).mappings.put(IListBox.fourcc(), IListBox.class);
        ((Boxes) this).mappings.put("mvex", NodeBox.class);
        ((Boxes) this).mappings.put("moof", NodeBox.class);
        ((Boxes) this).mappings.put("traf", NodeBox.class);
        ((Boxes) this).mappings.put("mfra", NodeBox.class);
        ((Boxes) this).mappings.put("skip", NodeBox.class);
        ((Boxes) this).mappings.put(MetaBox.fourcc(), MetaBox.class);
        ((Boxes) this).mappings.put(DataRefBox.fourcc(), DataRefBox.class);
        ((Boxes) this).mappings.put("ipro", NodeBox.class);
        ((Boxes) this).mappings.put("sinf", NodeBox.class);
        ((Boxes) this).mappings.put(ChunkOffsets64Box.fourcc(), ChunkOffsets64Box.class);
        ((Boxes) this).mappings.put(SoundMediaHeaderBox.fourcc(), SoundMediaHeaderBox.class);
        ((Boxes) this).mappings.put("clip", NodeBox.class);
        ((Boxes) this).mappings.put(ClipRegionBox.fourcc(), ClipRegionBox.class);
        ((Boxes) this).mappings.put(LoadSettingsBox.fourcc(), LoadSettingsBox.class);
        ((Boxes) this).mappings.put("tapt", NodeBox.class);
        ((Boxes) this).mappings.put("gmhd", NodeBox.class);
        ((Boxes) this).mappings.put("tmcd", Box.LeafBox.class);
        ((Boxes) this).mappings.put("tref", NodeBox.class);
        ((Boxes) this).mappings.put(ClearApertureBox.CLEF, ClearApertureBox.class);
        ((Boxes) this).mappings.put(ProductionApertureBox.PROF, ProductionApertureBox.class);
        ((Boxes) this).mappings.put(EncodedPixelBox.ENOF, EncodedPixelBox.class);
        ((Boxes) this).mappings.put(GenericMediaInfoBox.fourcc(), GenericMediaInfoBox.class);
        ((Boxes) this).mappings.put(TimecodeMediaInfoBox.fourcc(), TimecodeMediaInfoBox.class);
        ((Boxes) this).mappings.put(UdtaBox.fourcc(), UdtaBox.class);
        ((Boxes) this).mappings.put(CompositionOffsetsBox.fourcc(), CompositionOffsetsBox.class);
        ((Boxes) this).mappings.put(NameBox.fourcc(), NameBox.class);
        ((Boxes) this).mappings.put("mdta", Box.LeafBox.class);
        ((Boxes) this).mappings.put(MovieFragmentHeaderBox.fourcc(), MovieFragmentHeaderBox.class);
        ((Boxes) this).mappings.put(TrackFragmentHeaderBox.fourcc(), TrackFragmentHeaderBox.class);
        ((Boxes) this).mappings.put(MovieFragmentBox.fourcc(), MovieFragmentBox.class);
        ((Boxes) this).mappings.put(TrackFragmentBox.fourcc(), TrackFragmentBox.class);
        ((Boxes) this).mappings.put(TrackFragmentBaseMediaDecodeTimeBox.fourcc(), TrackFragmentBaseMediaDecodeTimeBox.class);
        ((Boxes) this).mappings.put(TrunBox.fourcc(), TrunBox.class);
        ((Boxes) this).mappings.put(MsrtBox.fourcc(), MsrtBox.class);
        ((Boxes) this).mappings.put(MtagBox.fourcc(), MtagBox.class);
    }
}
